### ISSUE TITLE
Smiley Face should follow Smiley Face convention

### ISSUE THREAD

**Issue by evenstensberg** [NikolaiMagnussen/fork-execv#1]
# Summary 

At [this line](https://github.com/NikolaiMagnussen/fork-execv/blob/master/src/main.rs#L48) I found a very disturbing use of smileys. As a smileyface patriot, I'm quite obsessed with smileys and this implementation breaks my heart. The code simply doesn't feel rite in my eyes without proper smileys, and also [Licensing](https://en.wikipedia.org/wiki/Smiley#Licensing_and_legal_issues) might be an issue. I highly suggest that you replace the smiley so that people won't get offended when reading the source code. [This](https://www.cs.cmu.edu/~sef/sefSmiley.htm) article explains smileyfaces in depth along with [this research paper](https://www.researchgate.net/publication/259103548_Research_on_Emoticons_Review_of_the_Field_and_Proposal_of_Research_Framework).

# Behaviour:

<details>
 <summary>Stacktrace</summary>
 Sleeping done - exiting now! :)
</details>

# Expected

<details>
 <summary>Stacktrace</summary>
Sleeping done - exiting now! :-)
</details>

---

I hope you prioritize this issue, as it's breaking my current implementation. God Bless :)

**Comment by NikolaiMagnussen** [comment]
Thank you for the friendly reminder.  I will try and resolve this issue at once.

**Comment by NikolaiMagnussen** [comment]
Resolved by 3b1ca47

**Comment by evenstensberg** [comment]
Thanks for fixing, our build is now passing 🎉
